! ------------------------------------------------------------------------------
! ROFI Color theme
! User: Rasi
! Copyright: Rasmus Steinke
! ------------------------------------------------------------------------------
rofi.color-enabled: true
rofi.color-window: #001112, #005741, #005741
rofi.color-normal: #001112, #c0e3e3, #003643, #00d6a1, #173535
rofi.color-active: #001112, #d66b00, #003643, #d66b00, #001112
rofi.color-urgent: #001112, #d60000, #003643, #d60000, #001112
