#!/bin/bash

HEIGHT=20
WIDTH=40
CHOICE_HEIGHT=10
TITLE="Configs"
MENU="Choose one of the following options:"

OPTIONS=(1 "polybar"
         2 "zsh"
         3 "i3"
         4 "compton"
         5 "vim"
         6 "ranger rifle"
         7 "ranger rc"
         8 "ranger commands"
         9 "rc"
         10 "dunst"
         11 "kitty")

CHOICE=$(dialog --clear \
                --title "$TITLE" \
                --menu "$MENU" \
                $HEIGHT $WIDTH $CHOICE_HEIGHT \
                "${OPTIONS[@]}" \
                2>&1 >/dev/tty)

clear
case $CHOICE in
        1)
            vim ~/.config/polybar/config
            ;;
        2)
            vim ~/.zshrc
            ;;
        3)
            vim ~/.config/i3/config
            ;;
        4)
            vim ~/.config/compton.conf
            ;;
        5)
            vim ~/.config/nvim/init.vim
            ;;
        6)
            vim ~/.config/ranger/rifle.conf
            ;;
        7)
            vim ~/.config/ranger/rc.conf
            ;;
        8)
            vim ~/.config/ranger/commands.py
            ;;
        9)
            vim ~/bin/rc
            ;;
        10)
            vim ~/.config/dunst/dunstrc
            ;;
        11)
            vim ~/.config/kitty/kitty.conf
            ;;
esac
